name: ChallengePlugin
version: 1.0
description: Challenge Plugin inspired from Banko
author: Keanu

main: de.keanu.main.Main

commands:
  settings:
    description: settings
    usage: /settings <setting>
  timer:
    description: timer
    usage: /timer <setting>