name: ChallengePlugin
version: 1.10
description: Challenge Plugin inspired from Banko
author: Keanu

main: de.keanu.main.Main

commands:
  settings:
    description: settings
    usage: /settings <setting>
  timer:
    description: timer
    usage: /timer <setting>
  warp:
    description: warp
    usage: /warp arg <name>
  backpack:
    description: shared Inventory
    usage: /backpack
  goal:
    description: setup goal
    usage: /goal <end/wither>